services:
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
      
  notification.api:
    image: notification.api
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile
      
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile

  checkings.api:
    image: checkings.api
    build:
      context: .
      dockerfile: Services/Checkings/Checkings.API/Dockerfile

  savings.api:
    image: savings.api
    build:
      context: .
      dockerfile: Services/Savings/Savings.API/Dockerfile

  authdb:
    image: mcr.microsoft.com/mssql/server
   
  usersdb:
    image: postgres
    
  checkingsdb:
    image: postgres

  savingsdb:
    image: postgres
    
  transactionsdb:
    image: mongo
    
  mongo-ui:
    image: mongo-express
  
  rabbitmq-broker:
    image: rabbitmq:3-management
    
  seq-logging:
    image: datalust/seq:latest
    
volumes:
  mssql-authdb:
  postgres-usersdb:
  postgres-checkingsdb:
  postgres-savingsdb:
  mongo-transactionsdb: