services:
  authdb:
    container_name: authdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
      - TZ=Europe/Kyiv
    ports:
      - "1433:1433"
    volumes:
      - mssql-authdb:/var/opt/mssql
  
  usersdb:
    container_name: usersdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=ifYouSeeThisThenHaveANiceDay
      - POSTGRES_USER=users.api
      - POSTGRES_DB=UsersDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-usersdb:/var/lib/postgresql/data
  
  checkingsdb:
    container_name: checkingsdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=ifYouSeeThisThenHaveANiceDay
      - POSTGRES_USER=checkings.api
      - POSTGRES_DB=CheckingsDb
    ports:
      - "5433:5432"
    volumes:
      - postgres-checkingsdb:/var/lib/postgresql/data
  
  auth.api:
    container_name: auth.api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AuthDb=Server=authdb;Database=AuthDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://nvm-bank-mb:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq-logging:5341
    ports:
      - "6000:8080"
    depends_on:
      - authdb
      - seq-logging
      - rabbitmq-broker
      - notification.api
  
  notification.api:
    container_name: notification.api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageBroker__Host=amqp://nvm-bank-mb:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq-logging:5341
    ports:
      - "6002:8080"
    depends_on:
      - rabbitmq-broker
  
  users.api:
    container_name: users.api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageBroker__Host=amqp://nvm-bank-mb:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq-logging:5341
      - ConnectionStrings__UsersDb=Server=usersdb;Port=5432;Database=UsersDb;User Id=users.api;Password=ifYouSeeThisThenHaveANiceDay;Include Error Detail=true
    ports:
      - "6001:8080"
    depends_on:
      - usersdb
      - rabbitmq-broker
      - seq-logging
      - notification.api
  
  checkings.api:
    container_name: checkings.api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - MessageBroker__Host=amqp://nvm-bank-mb:5672
      - Serilog__WriteTo__1__Args__serverUrl=http://seq-logging:5341
      - ConnectionStrings__CheckingsDb=Server=checkingsdb;Port=5432;Database=CheckingsDb;User Id=checkings.api;Password=ifYouSeeThisThenHaveANiceDay;Include Error Detail=true
    ports:
      - "6003:8080"
    depends_on:
      - checkingsdb
      - seq-logging
      - rabbitmq-broker
  
  rabbitmq-broker:
    container_name: rabbitmq-broker
    restart: always
    hostname: nvm-bank-mb
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  seq-logging:
    container_name: seq-logging
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"