services:
  authdb:
    container_name: authdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
      - TZ=Europe/Kyiv
    ports:
      - "1433:1433"
    volumes:
      - mssql-authdb:/var/opt/mssql
  
  usersdb:
    container_name: usersdb
    restart: always
    environment:
      - POSTGRES_PASSWORD=ifYouSeeThisThenHaveANiceDay
      - POSTGRES_USER=users.api
      - POSTGRES_DB=UsersDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-usersdb:/custom/data/directory
  
  auth.api:
    container_name: auth.api
    restart: always
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__AuthDb=Server=authdb;Database=AuthDb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - MessageBroker__Host=amqp://nvm-bank-mb:5672
    ports:
      - "6000:8080"
    depends_on:
      - authdb
  
  rabbitmq-broker:
    container_name: rabbitmq-broker
    restart: always
    hostname: nvm-bank-mb
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"