services:
  auth.api:
    image: auth.api
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
      
  notification.api:
    image: notification.api
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile
      
  users.api:
    image: users.api
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile

  authdb:
    image: mcr.microsoft.com/mssql/server
   
  usersdb:
    image: postgres
    
  checkingsdb:
    image: postgres
  
  rabbitmq-broker:
    image: rabbitmq:3-management
    
  seq-logging:
    image: datalust/seq:latest
    
volumes:
  mssql-authdb:
  postgres-usersdb:
  postgres-checkingsdb: